import React from 'react'
import Evaluation from './Form'
import Row from 'react-bootstrap/Row'
import Col from 'react-bootstrap/Col'
import Button from 'react-bootstrap/Button'
import ButtonToolbar from 'react-bootstrap/ButtonToolbar'
import Card from 'react-bootstrap/Card'
import CardGroup from 'react-bootstrap/CardGroup'
import Container from 'react-bootstrap/Container'
import Alert from 'react-bootstrap/Alert'


class Consent extends React.Component{
	
	constructor(props) {
		super(props);
		this.handleClick = this.handleClick.bind(this);
		this.onAlertClose = this.onAlertClose.bind(this);
		this.state = {
		  alert:null
		};
	  }
	  
	  onAlertClose(){
		  this.setState({
			  alert:null
		  });
	  }
	  
	  handleClick(e) {
		let btn=e.target.id
		let al=null
		if(btn==="no"){ //display error message
			al=<Alert variant="danger" dismissible onClose={this.onAlertClose}> In order to continue participating in the study, you must agree to give consent. </Alert>
		}else if(btn==="ok"){ //ok to participate. send msg to server. get an id for the session
			al=null
			this.props.giveConsent("CONSENT:OK")
		}
		
		this.setState({
				alert:al
		});
	  }
	  
	render() {
		 return (
		 <Container fluid={true}>
		 <Row>
			<Col sm>
			<Card>
			  <Card.Header><b>Consent to Participate in the Study</b></Card.Header>
			  <Card.Body>
				<Card.Text>
				<b>TITLE OF STUDY:</b> <br/>
				Understanding Intervention When Users Solve a Cognitively Engaging Rush Hour Puzzle<br/><br/>

				<b>PRINCIPAL INVESTIGATOR:</b><br/>
				Darrell Whitley, Ph.D., Professor<br/>
				Department of Computer Science<br/>
				L.Darrell.Whitley@ColoState.EDU <br/>
				(970) 491-5373<br/>
				<br/>
				<b>CO-PRINCIPAL INVESTIGATOR:</b><br/>
				Sachini Weerawardhana<br/>
				Department of Computer Science<br/>
				sachini@cs.colostate.edu<br/>
				(970) 818-6719<br/><br/>

				<b>WHY AM I BEING INVITED TO TAKE PART IN THIS RESEARCH?</b><br/>
				As a user of computers, your participation in this study will help the researchers understand how users interpret and understand explanations generated by an algorithm that explains an unexpected event.This understanding will lead to building user-friendly tools that are capable of assisting users to make safe decisions and avoid mistakes, while working on unfamiliar/complex domains. <br/>

				<b>WHO IS DOING THE STUDY? </b><br/>
				This study is being conducted by Darrell Whitley, Ph.D from the Computer Science Department, and Sachini  Weerawardhana, graduate student under his guidance. The software you will be using was developed by Sachini Weerawardhana.<br/>
				
				<b>WHAT IS THE PURPOSE OF THIS STUDY?</b><br/>
				The purpose of this study is to evaluate the quality of automatically generated explanations to develop tools that can act as automated assistants to the users in these situations. <br/>

				<b>WHERE IS THE STUDY GOING TO TAKE PLACE AND HOW LONG WILL IT LAST? </b><br/>
				Participation in this study is completely voluntary and you may stop at any time. If you agree to participate, you can visit the URL http:rushhourphase2.url and get started right away. You will be asked to watch 3 video recordings of sample game play instances. If you are not familiar with the Rush Hour game, a short tutorial is also provided on the web page.  Total expected time commitment is approximately 30 minutes. The study stops when you press the Quit button. You may withdraw participation at any time by clicking on a Quit button displayed on the web page without any penalty.<br/>

				<b>WHAT WILL I BE ASKED TO DO?</b><br/>
				If you agree to participate you will be:<br/>
					<ol>
						<li>given a brief introduction about the study and instructions on how to play the Rush Hour game.</li>
						
						<li>shown 3 videos of sample Rush Hour game plays and two types of explanations each game play generated. You will be asked to rate your satisfaction about the explanations.</li>
						
						<li>Shown a debriefing page to signal concluding the study and given contact information to answer any remaining concerns or questions you might have about the study.</li>
					</ol>
					You may withdraw participation at any time by  by clicking on a Quit button displayed on the web page and closing the web page without any penalty. <br/>
				
					<b>ARE THERE REASONS WHY I SHOULD NOT TAKE PART IN THIS STUDY?</b><br/>
					None.<br/>

				<b>WHAT ARE THE POSSIBLE RISKS AND DISCOMFORTS?</b><br/>
				There are no known or anticipated risks to you as a participant in this study other than those associated with the normal use of computers.<br/>
				It is not possible to identify all potential risks in research procedures, but the researcher(s) have taken reasonable safeguards to minimize any known and potential, but unknown, risks.<br/>

				<b>ARE THERE ANY BENEFITS FROM TAKING PART IN THIS STUDY?</b><br/>
				There are no direct benefits from participating in this study. However, the information you provide will help us understand how to improve software for common activities.<br/>

				<b>DO I HAVE TO TAKE PART IN THE STUDY?</b><br/>
				Your participation in this research is voluntary. If you decide to participate in the study, you may withdraw your consent and stop participating at any time without penalty or loss of benefits to which you are otherwise entitled.<br/>

				<b>WHO WILL SEE THE INFORMATION THAT I GIVE?</b><br/>
				We will keep private all research records that identify you, to the extent allowed by law. During the study, you will be randomly assigned a number that will mask any personally identifying information in the data that you will create. <br/>

				Your information will be combined with information from other people taking part in the study. When we write about the study to share it with other researchers, we will write about the combined information we have gathered. You will not be identified in these written materials. We may publish the results of this study; however, we will keep your name and other identifying information private.<br/>  
				The exception to this is if we are asked to share the research files for audit purposes with the CSU Institutional Review Board ethics committee. In addition, for funded studies, the CSU financial management team may also request an audit of research expenditures. For financial audits, only the fact that you participated would be shared, not any research data.<br/>

				All data collected is considered confidential. Even though we may publish our results in papers, only the principal and co-principal investigators will have access to the data collected. Your name or any other personal identifying information will not appear in any publication resulting from this study. <br/>

				Data collected during this study will be retained indefinitely in a secure location accessible only to the researchers.<br/>

				<b>WILL I RECEIVE ANY COMPENSATION FOR TAKING PART IN THIS STUDY?</b><br/>
				No<br/>


				<b>WHAT IF I HAVE QUESTIONS?</b><br/>
				If you have questions about the study, you can contact the investigator, Darrell Whitley at L.Darrell.Whitley@ColoState.EDU. <br/>If you have any questions about your rights as a volunteer in this research, contact the CSU IRB at:  RICRO_IRB@mail.colostate.edu; 970-491-1553.<br/>

				<b>CONSENT: </b><br/>
				I agree to participate in a study titled Understanding Intervention When Users Solve a Cognitively Engaging Rush Hour Puzzle at Colorado State University. I have made this decision based on the information I have read in this Information-Consent Letter and have had the opportunity to receive any additional details I wanted about the study. I understand that I may withdraw this consent at any time by instructing the researcher. <br/>

				I am aware that excerpts from the interview and/or may be included in any publications to come from this study, with the understanding that the quotations will be anonymous.<br/>

				I am aware that I may withdraw this consent at any time without penalty. I was informed that I may withdraw my consent at any time without penalty by advising the researcher.<br/>

				I agree to the use of anonymous quotations in any presentation or report that comes of this study.<br/>
				<br/>
				<i>By clicking on the I agree button you acknowledge that you have read the information stated and willingly signed this consent form.</i><br/>

				</Card.Text>
				<ButtonToolbar>
				    <Button variant="success" id="ok" onClick={this.handleClick}>I agree</Button> &nbsp; &nbsp; &nbsp;
				    <Button variant="danger" id="no" onClick={this.handleClick}>I do not agree</Button>
				</ButtonToolbar>
				{this.state.alert}				
			  </Card.Body>
			</Card>
			</Col>		
		 </Row>
		 
		</Container> 
	  );
	}
}export default Consent;
